### PR TITLE
feat: change default executor to cypress/base:12.19.0

### PR DESCRIPTION
**Pull request by flotwig**
With Cypress 7, the orb fails with the default configuration, since Node 10 is no longer supported by Cypress:

https://app.circleci.com/pipelines/github/cypress-io/angular-pizza-creator/319/workflows/a777b065-1cdd-46a5-8d2b-1abcbc711412/jobs/321

This PR updates the default executor to use Node 12 so that it works ootb with Cypress 7.

### CODE REVIEW

**Comment by bahmutov** [comment]
should we just set it to node 14 already?

**Comment by flotwig** [comment]
12 is the minimum required by Cypress 7.

**Comment by flotwig** [comment]
@bahmutov how can i update these snapshots? i tried running `npm run manual:tests -u` locally, but i get errors like this for all tests:
 
image

same for `npm test`

**Comment by bahmutov** [comment]
I just think it is weird to change to Node 12 to _bare_ minimum version rather than LTS version?

**Comment by flotwig** [comment]
Wasn't it Node 10 previously because that was the minimum required by Cypress? This is keeping with tradition. I guess we could switch to using the latest LTS but I don't see why it matters one way or the other

**Comment by bahmutov** [comment]
I think the tradition was only an artifact of Node 12 being released :) Keeping to 12.0.0 is like asking someone to install Cypress v6 and they install specifically Cypress v6.0.0 and you are like "why...." There are lots of fixes and features in the LTS compared to the first major release. I say, let me make this PR on top of the latest 12 we have.

**Comment by flotwig** [comment]
Updated to cypress/base:12.19.0.

**Comment by bahmutov** [comment]
Yeah, let me update the snapshots

**Comment by flotwig** [comment]
**https://github.com/cypress-io/circleci-orb/pull/339**

**Pull request closed without merging**
