### PR TITLE
Explain docker images and custom executors

### PR DESCRIPTION
**Pull request by bahmutov**

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
I interlinked more sections and added a link to default orb executors. Also updated Chrome example since I imagine this is commonly used and everyone likely wants to use a custom executor for this.

**Comment by bahmutov** [comment]
ughh @jennifer-shehane docs/examples is auto generated from src/orb.yml - these are examples plus a little of the wrapper code. If you run `npm run docs` your example md is overwritten back to the previous one

**Comment by bahmutov** [comment]
https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#examples

**Comment by jennifer-shehane** [comment]
😅 oh boy. I'll look at it after this meeting.

**Comment by jennifer-shehane** [comment]
@bahmutov I updated if you want to review again.

**Comment by bahmutov** [comment]
nice, merging it in

**Pull request merged**
