### PR TITLE
chore: set circleci browser tools orb to pull v1 with updates

### PR DESCRIPTION
**Pull request by DaleGardner**
Pin the version @1 so that non-breaking updates and fixes can be pulled in automatically as they arise.

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]

**Review by maksr13 — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@DaleGardner The tests don't appear to be running and I'm not sure why

**Comment by DaleGardner** [comment]
> @DaleGardner The tests don't appear to be running and I'm not sure why

@jennifer-shehane My guess is that it's something to do with this being an outside collaborator contribution. All the recent pipeline runs I see are from org members. The pipelines are not even triggering so maybe the project is not set to run a pipeline for a fork?

**Comment by jennifer-shehane** [comment]
@DaleGardner That must be it! Updated circleci settings, let me try to commit to rerun. You forget all these little steps for newer projects.

**Comment by DaleGardner** [comment]
> @DaleGardner That must be it! Updated circleci settings, let me try to commit to rerun. You forget all these little steps for newer projects.

Seems like you might also need the option for setting secrets for forked builds to pass the token

**Comment by jennifer-shehane** [comment]
@DaleGardner We don't want to expose this secret in forked builds, but I was able to trigger this to run.

**Comment by jennifer-shehane** [comment]
Sorry for the delay, haven't touched this repo in a while!

**Comment by sedghi** [comment]
@jennifer-shehane Thanks for the merge, I think you need to manually release it as well? since I still see 3.2 being the last release

https://github.com/cypress-io/circleci-orb/releases

**Comment by MikeMcC399** [comment]
There is a section in [CONTRIBUTING > Releasing](https://github.com/cypress-io/circleci-orb/blob/master/CONTRIBUTING.md#releasing) describing the manual steps necessary to release.

Merging a PR apparently only triggers a `test-deploy` in the [CircleCI Pipeline](https://app.circleci.com/pipelines/github/cypress-io/circleci-orb).

**Comment by sedghi** [comment]
@MikeMcC399 Yeah need to be done by maintainers

**Pull request merged**
