### PR TITLE
bumping node orb to enable pnpm

### LINKED ISSUE #442: package manager:PNPM not supported in circleci orb
Hey all,
Just wanted to ask, when will circleci orb support pnpm as well. Currently working on a project which is using pnpm, would like to run cypress in ci and it would be definitely easier if pnpm would be supported as well.

Thanks a lot!
Petra

### PR DESCRIPTION
**Pull request by ramykl**
Closes #442

### CODE REVIEW

**Comment by ramykl** [comment]
@jennifer-shehane able to get someone to have a look at this small PR?

**Comment by MikeMcC399** [comment]
@ramykl 

> It would be really good to get this merged so `pnpm` is finally working as described in the readme for this

Sorry that I can't help here. I'm an external contributor and I have no privileges to merge PRs or to release new versions of the Orb. Such actions need to be handled by the Cypress.io team themselves.

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@ramykl The pnpm example is failing here: https://app.circleci.com/pipelines/github/cypress-io/circleci-orb/1978/workflows/b9ff5b12-b6f0-479a-a4de-083b3330e676/jobs/7020

**Comment by ramykl** [comment]
@jennifer-shehane I'm trying to track down why it's failing.... for whatever reason it's install version 8 of pnpm instead of version 9... but can't see any reason why in either the node orb or the circleci-orb... will provide a fix whenever I can track it down

**Comment by ramykl** [comment]
@jennifer-shehane I think this #492 will fix the failing test

**Pull request merged**
