### PR TITLE
Corrected minor grammatical/spelling error

### PR DESCRIPTION
**Pull request by purifyyourhome**

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey @purifyyourhome Thanks for the contribution! Could you please sign our CLA?

**Comment by purifyyourhome** [comment]
Thanks. Just signed

Tue Oct 29 17:26:53 EDT 2019 CLAassistant <notifications@github.com>:

**Comment by bahmutov** [comment]
hmm, weird, but CLA still thinks it is unsigned

**Comment by purifyyourhome** [comment]
Just tried signing again via the website.  If it didn't take again, I'm happy to record a video to show the process. I am using Firefox Release 70.0.1 on Mac OS X 10.13.6.

Best,

purifyyourhome




On Wednesday, November 6, 2019, 11:49:09 AM MST, Gleb Bahmutov <notifications@github.com> wrote: 





hmm, weird, but CLA still thinks it is unsigned

**Comment by jennifer-shehane** [comment]
Thanks for signing the CLA, unfortunately the author of the commits (DELL) does not match the email address on your GitHub account (purifyyourhome). Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by bahmutov** [comment]
closing for now since CLA not signed

**Pull request closed without merging**
